apiVersion: apps/v1
kind: Deployment
metadata:
  name: pal-tracker
spec:
  template:
    spec:
      containers:
        - name: pal-tracker-container
          image: vmwarevarunrai/pal-tracker:build-15
          env:
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE
              valueFrom:
                configMapKeyRef:
                  name: pal-tracker
                  key: spring.datasource.hikari.maximumpoolsize